from exts import db

class User(db.Model):
    __tablename__="user"
    id=db.Column(db.Integer ,primary_key=True, autoincrement=True)
    username = db.Column(db.String(100), nullable=False)
    password = db.Column(db.String(200), nullable=False)
    email = db.Column(db.String(100),nullable=False)
    identity=db.Column(db.String(100),nullable=False)
class email_captcha(db.Model):
    __tablename__="email_captcha"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(100), nullable=False, unique=True)
    captcha=db.Column(db.String(100),nullable=False)
class journeydatamodel(db.Model):
    __tablename__ = "journeydata"
    id=db.Column(db.Integer)
    journeyid=db.Column(db.Integer,primary_key=True,autoincrement=True)
    submittime=db.Column(db.String(100),nullable=False)
    time = db.Column(db.String(100),nullable=False)
    orig1_1=db.Column(db.String(100), nullable=True)
    dest1_1=db.Column(db.String(100), nullable=True)
    orig1_2 = db.Column(db.String(100), nullable=True)
    dest1_2 = db.Column(db.String(100), nullable=True)
    orig1_3 = db.Column(db.String(100), nullable=True)
    dest1_3 = db.Column(db.String(100), nullable=True)
    orig1_4 = db.Column(db.String(100), nullable=True)
    dest1_4 = db.Column(db.String(100), nullable=True)
    orig1_5 = db.Column(db.String(100), nullable=True)
    dest1_5 = db.Column(db.String(100), nullable=True)
    orig1_6 = db.Column(db.String(100), nullable=True)
    dest1_6 = db.Column(db.String(100), nullable=True)
    orig1_7 = db.Column(db.String(100), nullable=True)
    dest1_7 = db.Column(db.String(100), nullable=True)
    orig1_8 = db.Column(db.String(100), nullable=True)
    dest1_8 = db.Column(db.String(100), nullable=True)
    orig1_9 = db.Column(db.String(100), nullable=True)
    dest1_9 = db.Column(db.String(100), nullable=True)
    orig1_10 = db.Column(db.String(100), nullable=True)
    dest1_10 = db.Column(db.String(100), nullable=True)
    orig1_11 = db.Column(db.String(100), nullable=True)
    dest1_11 = db.Column(db.String(100), nullable=True)


    orig2_1 = db.Column(db.String(100), nullable=True)
    dest2_1 = db.Column(db.String(100), nullable=True)
    orig2_2 = db.Column(db.String(100), nullable=True)
    dest2_2 = db.Column(db.String(100), nullable=True)
    orig2_3 = db.Column(db.String(100), nullable=True)
    dest2_3 = db.Column(db.String(100), nullable=True)
    orig2_4 = db.Column(db.String(100), nullable=True)
    dest2_4 = db.Column(db.String(100), nullable=True)
    orig2_5 = db.Column(db.String(100), nullable=True)
    dest2_5 = db.Column(db.String(100), nullable=True)
    orig2_6 = db.Column(db.String(100), nullable=True)
    dest2_6 = db.Column(db.String(100), nullable=True)
    orig2_7 = db.Column(db.String(100), nullable=True)
    dest2_7 = db.Column(db.String(100), nullable=True)
    orig2_8 = db.Column(db.String(100), nullable=True)
    dest2_8 = db.Column(db.String(100), nullable=True)
    orig2_9 = db.Column(db.String(100), nullable=True)
    dest2_9 = db.Column(db.String(100), nullable=True)
    orig2_10 = db.Column(db.String(100), nullable=True)
    dest2_10 = db.Column(db.String(100), nullable=True)
    orig2_11 = db.Column(db.String(100), nullable=True)
    dest2_11 = db.Column(db.String(100), nullable=True)


    orig3_1 = db.Column(db.String(100), nullable=True)
    dest3_1 = db.Column(db.String(100), nullable=True)
    orig3_2 = db.Column(db.String(100), nullable=True)
    dest3_2 = db.Column(db.String(100), nullable=True)
    orig3_3 = db.Column(db.String(100), nullable=True)
    dest3_3 = db.Column(db.String(100), nullable=True)
    orig3_4 = db.Column(db.String(100), nullable=True)
    dest3_4 = db.Column(db.String(100), nullable=True)
    orig3_5 = db.Column(db.String(100), nullable=True)
    dest3_5 = db.Column(db.String(100), nullable=True)
    orig3_6 = db.Column(db.String(100), nullable=True)
    dest3_6 = db.Column(db.String(100), nullable=True)
    orig3_7 = db.Column(db.String(100), nullable=True)
    dest3_7 = db.Column(db.String(100), nullable=True)
    orig3_8 = db.Column(db.String(100), nullable=True)
    dest3_8 = db.Column(db.String(100), nullable=True)
    orig3_9 = db.Column(db.String(100), nullable=True)
    dest3_9 = db.Column(db.String(100), nullable=True)
    orig3_10 = db.Column(db.String(100), nullable=True)
    dest3_10 = db.Column(db.String(100), nullable=True)
    orig3_11 = db.Column(db.String(100), nullable=True)
    dest3_11 = db.Column(db.String(100), nullable=True)

    orig4_1 = db.Column(db.String(100), nullable=True)
    dest4_1 = db.Column(db.String(100), nullable=True)
    orig4_2 = db.Column(db.String(100), nullable=True)
    dest4_2 = db.Column(db.String(100), nullable=True)
    orig4_3 = db.Column(db.String(100), nullable=True)
    dest4_3 = db.Column(db.String(100), nullable=True)
    orig4_4 = db.Column(db.String(100), nullable=True)
    dest4_4 = db.Column(db.String(100), nullable=True)
    orig4_5 = db.Column(db.String(100), nullable=True)
    dest4_5 = db.Column(db.String(100), nullable=True)
    orig4_6 = db.Column(db.String(100), nullable=True)
    dest4_6 = db.Column(db.String(100), nullable=True)
    orig4_7 = db.Column(db.String(100), nullable=True)
    dest4_7 = db.Column(db.String(100), nullable=True)
    orig4_8 = db.Column(db.String(100), nullable=True)
    dest4_8 = db.Column(db.String(100), nullable=True)
    orig4_9 = db.Column(db.String(100), nullable=True)
    dest4_9 = db.Column(db.String(100), nullable=True)
    orig4_10 = db.Column(db.String(100), nullable=True)
    dest4_10 = db.Column(db.String(100), nullable=True)
    orig4_11 = db.Column(db.String(100), nullable=True)
    dest4_11 = db.Column(db.String(100), nullable=True)

    orig5_1 = db.Column(db.String(100), nullable=True)
    dest5_1 = db.Column(db.String(100), nullable=True)
    orig5_2 = db.Column(db.String(100), nullable=True)
    dest5_2 = db.Column(db.String(100), nullable=True)
    orig5_3 = db.Column(db.String(100), nullable=True)
    dest5_3 = db.Column(db.String(100), nullable=True)
    orig5_4 = db.Column(db.String(100), nullable=True)
    dest5_4 = db.Column(db.String(100), nullable=True)
    orig5_5 = db.Column(db.String(100), nullable=True)
    dest5_5 = db.Column(db.String(100), nullable=True)
    orig5_6 = db.Column(db.String(100), nullable=True)
    dest5_6 = db.Column(db.String(100), nullable=True)
    orig5_7 = db.Column(db.String(100), nullable=True)
    dest5_7 = db.Column(db.String(100), nullable=True)
    orig5_8 = db.Column(db.String(100), nullable=True)
    dest5_8 = db.Column(db.String(100), nullable=True)
    orig5_9 = db.Column(db.String(100), nullable=True)
    dest5_9 = db.Column(db.String(100), nullable=True)
    orig5_10 = db.Column(db.String(100), nullable=True)
    dest5_10 = db.Column(db.String(100), nullable=True)
    orig5_11 = db.Column(db.String(100), nullable=True)
    dest5_11 = db.Column(db.String(100), nullable=True)


class test(db.Model):
    __tablename__="test"
    id=db.Column(db.Integer ,primary_key=True,autoincrement=True)
class bikedata(db.Model):
    __tablename__="bikedata"
    id=db.Column(db.Integer ,primary_key=True,autoincrement=True)
    midzone_1=db.Column(db.String(100))
    midzone_2=db.Column(db.String(100))
    midcanteen=db.Column(db.String(100))
    east_1teach=db.Column(db.String(100))
    east_2teach=db.Column(db.String(100))
    east_5teach=db.Column(db.String(100))
    eastlib=db.Column(db.String(100))
    eastground=db.Column(db.String(100))
    eastyuan=db.Column(db.String(100))
    eastlihua=db.Column(db.String(100))
    easthospi=db.Column(db.String(100))
    eastzone_1=db.Column(db.String(100))
    eastzone_2=db.Column(db.String(100))
    eastlitang=db.Column(db.String(100))
    westlib=db.Column(db.String(100))
    west_3teach=db.Column(db.String(100))
    westzone_1=db.Column(db.String(100))
    westzone_2=db.Column(db.String(100))
    westcanteen=db.Column(db.String(100))


class comment(db.Model):
    __tablename__="comment"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    sender=db.Column(db.String(100))
    senderid=db.Column(db.String(100))
    accepter=db.Column(db.String(100))
    text=db.Column(db.String(250))
    isread=db.Column(db.String(10))
    isreplied=db.Column(db.String(10))
    time=db.Column(db.String(100))
class reply(db.Model):
    __tablename__="reply"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    tocommentid=db.Column(db.String(100))
    sender=db.Column(db.String(100))
    sendername=db.Column(db.String(100))
    accepter=db.Column(db.String(100))
    text = db.Column(db.String(250))
    isread = db.Column(db.String(10))
    time = db.Column(db.String(100))
    isdeleted=db.Column(db.String(10))


