"""empty message

Revision ID: 44bdeb4fea83
Revises: 799929e39bd5
Create Date: 2024-11-12 14:30:10.872010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44bdeb4fea83'
down_revision = '799929e39bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upgradesignal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isupgrade', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upgradesignal')
    # ### end Alembic commands ###
