"""empty message

Revision ID: 4b9b0e172ee3
Revises: 
Create Date: 2024-09-02 22:02:35.610569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9b0e172ee3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('journeydata',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('journeyid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submittime', sa.String(length=100), nullable=False),
    sa.Column('time', sa.String(length=100), nullable=False),
    sa.Column('orig1_1', sa.String(length=100), nullable=True),
    sa.Column('dest1_1', sa.String(length=100), nullable=True),
    sa.Column('orig1_2', sa.String(length=100), nullable=True),
    sa.Column('dest1_2', sa.String(length=100), nullable=True),
    sa.Column('orig1_3', sa.String(length=100), nullable=True),
    sa.Column('dest1_3', sa.String(length=100), nullable=True),
    sa.Column('orig1_4', sa.String(length=100), nullable=True),
    sa.Column('dest1_4', sa.String(length=100), nullable=True),
    sa.Column('orig1_5', sa.String(length=100), nullable=True),
    sa.Column('dest1_5', sa.String(length=100), nullable=True),
    sa.Column('orig1_6', sa.String(length=100), nullable=True),
    sa.Column('dest1_6', sa.String(length=100), nullable=True),
    sa.Column('orig1_7', sa.String(length=100), nullable=True),
    sa.Column('dest1_7', sa.String(length=100), nullable=True),
    sa.Column('orig1_8', sa.String(length=100), nullable=True),
    sa.Column('dest1_8', sa.String(length=100), nullable=True),
    sa.Column('orig1_9', sa.String(length=100), nullable=True),
    sa.Column('dest1_9', sa.String(length=100), nullable=True),
    sa.Column('orig1_10', sa.String(length=100), nullable=True),
    sa.Column('dest1_10', sa.String(length=100), nullable=True),
    sa.Column('orig1_11', sa.String(length=100), nullable=True),
    sa.Column('dest1_11', sa.String(length=100), nullable=True),
    sa.Column('orig2_1', sa.String(length=100), nullable=True),
    sa.Column('dest2_1', sa.String(length=100), nullable=True),
    sa.Column('orig2_2', sa.String(length=100), nullable=True),
    sa.Column('dest2_2', sa.String(length=100), nullable=True),
    sa.Column('orig2_3', sa.String(length=100), nullable=True),
    sa.Column('dest2_3', sa.String(length=100), nullable=True),
    sa.Column('orig2_4', sa.String(length=100), nullable=True),
    sa.Column('dest2_4', sa.String(length=100), nullable=True),
    sa.Column('orig2_5', sa.String(length=100), nullable=True),
    sa.Column('dest2_5', sa.String(length=100), nullable=True),
    sa.Column('orig2_6', sa.String(length=100), nullable=True),
    sa.Column('dest2_6', sa.String(length=100), nullable=True),
    sa.Column('orig2_7', sa.String(length=100), nullable=True),
    sa.Column('dest2_7', sa.String(length=100), nullable=True),
    sa.Column('orig2_8', sa.String(length=100), nullable=True),
    sa.Column('dest2_8', sa.String(length=100), nullable=True),
    sa.Column('orig2_9', sa.String(length=100), nullable=True),
    sa.Column('dest2_9', sa.String(length=100), nullable=True),
    sa.Column('orig2_10', sa.String(length=100), nullable=True),
    sa.Column('dest2_10', sa.String(length=100), nullable=True),
    sa.Column('orig2_11', sa.String(length=100), nullable=True),
    sa.Column('dest2_11', sa.String(length=100), nullable=True),
    sa.Column('orig3_1', sa.String(length=100), nullable=True),
    sa.Column('dest3_1', sa.String(length=100), nullable=True),
    sa.Column('orig3_2', sa.String(length=100), nullable=True),
    sa.Column('dest3_2', sa.String(length=100), nullable=True),
    sa.Column('orig3_3', sa.String(length=100), nullable=True),
    sa.Column('dest3_3', sa.String(length=100), nullable=True),
    sa.Column('orig3_4', sa.String(length=100), nullable=True),
    sa.Column('dest3_4', sa.String(length=100), nullable=True),
    sa.Column('orig3_5', sa.String(length=100), nullable=True),
    sa.Column('dest3_5', sa.String(length=100), nullable=True),
    sa.Column('orig3_6', sa.String(length=100), nullable=True),
    sa.Column('dest3_6', sa.String(length=100), nullable=True),
    sa.Column('orig3_7', sa.String(length=100), nullable=True),
    sa.Column('dest3_7', sa.String(length=100), nullable=True),
    sa.Column('orig3_8', sa.String(length=100), nullable=True),
    sa.Column('dest3_8', sa.String(length=100), nullable=True),
    sa.Column('orig3_9', sa.String(length=100), nullable=True),
    sa.Column('dest3_9', sa.String(length=100), nullable=True),
    sa.Column('orig3_10', sa.String(length=100), nullable=True),
    sa.Column('dest3_10', sa.String(length=100), nullable=True),
    sa.Column('orig3_11', sa.String(length=100), nullable=True),
    sa.Column('dest3_11', sa.String(length=100), nullable=True),
    sa.Column('orig4_1', sa.String(length=100), nullable=True),
    sa.Column('dest4_1', sa.String(length=100), nullable=True),
    sa.Column('orig4_2', sa.String(length=100), nullable=True),
    sa.Column('dest4_2', sa.String(length=100), nullable=True),
    sa.Column('orig4_3', sa.String(length=100), nullable=True),
    sa.Column('dest4_3', sa.String(length=100), nullable=True),
    sa.Column('orig4_4', sa.String(length=100), nullable=True),
    sa.Column('dest4_4', sa.String(length=100), nullable=True),
    sa.Column('orig4_5', sa.String(length=100), nullable=True),
    sa.Column('dest4_5', sa.String(length=100), nullable=True),
    sa.Column('orig4_6', sa.String(length=100), nullable=True),
    sa.Column('dest4_6', sa.String(length=100), nullable=True),
    sa.Column('orig4_7', sa.String(length=100), nullable=True),
    sa.Column('dest4_7', sa.String(length=100), nullable=True),
    sa.Column('orig4_8', sa.String(length=100), nullable=True),
    sa.Column('dest4_8', sa.String(length=100), nullable=True),
    sa.Column('orig4_9', sa.String(length=100), nullable=True),
    sa.Column('dest4_9', sa.String(length=100), nullable=True),
    sa.Column('orig4_10', sa.String(length=100), nullable=True),
    sa.Column('dest4_10', sa.String(length=100), nullable=True),
    sa.Column('orig4_11', sa.String(length=100), nullable=True),
    sa.Column('dest4_11', sa.String(length=100), nullable=True),
    sa.Column('orig5_1', sa.String(length=100), nullable=True),
    sa.Column('dest5_1', sa.String(length=100), nullable=True),
    sa.Column('orig5_2', sa.String(length=100), nullable=True),
    sa.Column('dest5_2', sa.String(length=100), nullable=True),
    sa.Column('orig5_3', sa.String(length=100), nullable=True),
    sa.Column('dest5_3', sa.String(length=100), nullable=True),
    sa.Column('orig5_4', sa.String(length=100), nullable=True),
    sa.Column('dest5_4', sa.String(length=100), nullable=True),
    sa.Column('orig5_5', sa.String(length=100), nullable=True),
    sa.Column('dest5_5', sa.String(length=100), nullable=True),
    sa.Column('orig5_6', sa.String(length=100), nullable=True),
    sa.Column('dest5_6', sa.String(length=100), nullable=True),
    sa.Column('orig5_7', sa.String(length=100), nullable=True),
    sa.Column('dest5_7', sa.String(length=100), nullable=True),
    sa.Column('orig5_8', sa.String(length=100), nullable=True),
    sa.Column('dest5_8', sa.String(length=100), nullable=True),
    sa.Column('orig5_9', sa.String(length=100), nullable=True),
    sa.Column('dest5_9', sa.String(length=100), nullable=True),
    sa.Column('orig5_10', sa.String(length=100), nullable=True),
    sa.Column('dest5_10', sa.String(length=100), nullable=True),
    sa.Column('orig5_11', sa.String(length=100), nullable=True),
    sa.Column('dest5_11', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('journeyid')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('test')
    op.drop_table('journeydata')
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
