"""empty message

Revision ID: 4f298c65723e
Revises: 6d901c24e4fc
Create Date: 2024-10-29 20:45:48.182105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f298c65723e'
down_revision = '6d901c24e4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isdeleted', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_column('isdeleted')

    # ### end Alembic commands ###
