"""empty message

Revision ID: 5a5e806ec0ee
Revises: fcdeb699c934
Create Date: 2024-09-09 19:53:01.649148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5e806ec0ee'
down_revision = 'fcdeb699c934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikedata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('midzone_1', sa.String(length=100), nullable=True),
    sa.Column('midzone_2', sa.String(length=100), nullable=True),
    sa.Column('midcanteen', sa.String(length=100), nullable=True),
    sa.Column('east_1teach', sa.String(length=100), nullable=True),
    sa.Column('east_2teach', sa.String(length=100), nullable=True),
    sa.Column('east_5teach', sa.String(length=100), nullable=True),
    sa.Column('eastlib', sa.String(length=100), nullable=True),
    sa.Column('eastground', sa.String(length=100), nullable=True),
    sa.Column('eastyuan', sa.String(length=100), nullable=True),
    sa.Column('eastlihua', sa.String(length=100), nullable=True),
    sa.Column('easthospi', sa.String(length=100), nullable=True),
    sa.Column('eastzone_1', sa.String(length=100), nullable=True),
    sa.Column('eastzone_2', sa.String(length=100), nullable=True),
    sa.Column('eastlitang', sa.String(length=100), nullable=True),
    sa.Column('westlib', sa.String(length=100), nullable=True),
    sa.Column('west_3teach', sa.String(length=100), nullable=True),
    sa.Column('westzone_1', sa.String(length=100), nullable=True),
    sa.Column('westzone_2', sa.String(length=100), nullable=True),
    sa.Column('westcanteen', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bikedata')
    # ### end Alembic commands ###
