"""empty message

Revision ID: 655ff2912327
Revises: cd22f564254a
Create Date: 2024-10-21 20:41:38.427553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655ff2912327'
down_revision = 'cd22f564254a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tocommentid', sa.String(length=100), nullable=True),
    sa.Column('sender', sa.String(length=100), nullable=True),
    sa.Column('accepter', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(length=250), nullable=True),
    sa.Column('isread', sa.String(length=10), nullable=True),
    sa.Column('time', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    # ### end Alembic commands ###
