"""empty message

Revision ID: 6d901c24e4fc
Revises: 73003c0f06fc
Create Date: 2024-10-23 20:29:25.193161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d901c24e4fc'
down_revision = '73003c0f06fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sendername', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_column('sendername')

    # ### end Alembic commands ###
