"""empty message

Revision ID: 73003c0f06fc
Revises: b94f4569de4d
Create Date: 2024-10-23 19:21:56.015407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73003c0f06fc'
down_revision = 'b94f4569de4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senderid', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('senderid')

    # ### end Alembic commands ###
