"""empty message

Revision ID: 799929e39bd5
Revises: 4f298c65723e
Create Date: 2024-11-12 14:27:23.321464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799929e39bd5'
down_revision = '4f298c65723e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orig', sa.String(length=100), nullable=True),
    sa.Column('dest', sa.String(length=100), nullable=True),
    sa.Column('numb', sa.String(length=100), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestion')
    # ### end Alembic commands ###
