"""empty message

Revision ID: a0a30c47562a
Revises: 5a5e806ec0ee
Create Date: 2024-09-17 16:22:57.800576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a30c47562a'
down_revision = '5a5e806ec0ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=True),
    sa.Column('accepter', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(length=250), nullable=True),
    sa.Column('isread', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
