"""empty message

Revision ID: b892be72a2ab
Revises: 44bdeb4fea83
Create Date: 2024-11-12 14:32:22.672874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b892be72a2ab'
down_revision = '44bdeb4fea83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upgradesignal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upgradesignal', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
